/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*
 * Hand-written boot code for the chat sidebar, kept OUTSIDE init.js on
 * purpose: init.js is regenerated by trunk + fix-csp.sh on every dioxus
 * rebuild (fix-csp overwrites it with the extracted wasm loader), which used
 * to clobber these handlers until they were re-merged by hand. This file is
 * hand-maintained in wasm/chat-sidebar/ (like nf-theme.css/theme-color.mjs)
 * and referenced by a plain <script> tag in the trunk source index.html, so
 * rebuilds keep the reference and never touch the content.
 */

// Maximize button click handler - MUST be synchronous to preserve user gesture
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.maximize-btn');
        if (!button) return;

        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('mode') === 'maximized') return;

        event.preventDefault();
        event.stopPropagation();

        console.log('[NevoFlux] Maximize clicked - synchronous handler');

        // Get data SYNCHRONOUSLY from window globals (set by WASM)
        const sessionId = window.__nevoflux_session_id || '';
        const targetTabId = window.__nevoflux_target_tab_id || 0;

        // Build URL synchronously
        const baseUrl = window.location.href.split('?')[0];
        const newUrl = `${baseUrl}?mode=maximized&session_id=${sessionId}&target_tab_id=${targetTabId}&source_tab_id=${targetTabId}`;

        console.log('[NevoFlux] Opening maximized view:', newUrl);

        // Open tab FIRST using window.open (synchronous, executes before close destroys context)
        window.open(newUrl, '_blank');

        // Then close sidebar (user gesture still valid since no await yet)
        if (browser.sidebarAction && browser.sidebarAction.close) {
            browser.sidebarAction.close().catch(e => console.warn('[NevoFlux] close failed:', e));
        }
    }, true); // capture phase
})();

// Restore button click handler - MUST be synchronous to preserve user gesture
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.restore-btn');
        if (!button) return;

        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('mode') !== 'maximized') return;

        event.preventDefault();
        event.stopPropagation();

        console.log('[NevoFlux] Restore clicked - synchronous handler');

        // Get source_tab_id from URL params
        const sourceTabId = parseInt(urlParams.get('source_tab_id')) || 0;

        // Open sidebar FIRST - this requires user gesture
        if (browser.sidebarAction && browser.sidebarAction.open) {
            browser.sidebarAction.open().catch(e => console.warn('[NevoFlux] open failed:', e));
        }

        // Then activate source tab and close this tab (no user gesture needed)
        if (sourceTabId > 0) {
            browser.tabs.update(sourceTabId, { active: true }).catch(e => console.warn('[NevoFlux] activate tab failed:', e));
        }

        // Close current maximized tab
        browser.tabs.getCurrent().then(tab => {
            if (tab && tab.id) {
                browser.tabs.remove(tab.id).catch(e => console.warn('[NevoFlux] close tab failed:', e));
            }
        }).catch(e => console.warn('[NevoFlux] get current tab failed:', e));
    }, true); // capture phase
})();

// Minimize button click handler - MUST be synchronous to preserve user gesture.
// Mirrors the maximize handler above: this file owns the whole minimize flow in
// plain JS because the extension CSP (script-src 'self' 'wasm-unsafe-eval') blocks
// js_sys::eval, which is why the Rust try_close_sidebar_sync() close was a silent
// no-op. Capture-phase + stopPropagation bypasses the Dioxus onclick so this runs
// once and there is no double-send.
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.minimize-btn');
        if (!button) return;

        event.preventDefault();
        event.stopPropagation();

        const urlParams = new URLSearchParams(window.location.search);
        const isMaximized = urlParams.get('mode') === 'maximized';

        console.log('[NevoFlux] Minimize clicked - synchronous handler (maximized=' + isMaximized + ')');

        // Gather session context so the background can restore the right session when
        // the avatar Maximize button is clicked. Window globals cover sidebar mode;
        // URL params cover the maximized-tab mode (mirroring how the maximize handler
        // sources them in the sidebar branch above).
        const sessionId = window.__nevoflux_session_id || urlParams.get('session_id') || '';
        const targetTabId = window.__nevoflux_target_tab_id || parseInt(urlParams.get('target_tab_id') || '0', 10) || 0;

        // Notify the background FIRST to show the floating avatar + start the daemon
        // keepalive. sendMessage returns a Promise, but the send itself is dispatched
        // synchronously to the browser IPC while the gesture is still active, so the
        // message survives the imminent teardown from the close/remove below.
        if (browser.runtime && browser.runtime.sendMessage) {
            browser.runtime.sendMessage({ type: 'bg:agent_minimize', session_id: sessionId, target_tab_id: targetTabId }).catch(e => console.warn('[NevoFlux] minimize sendMessage failed:', e));
        }

        if (isMaximized) {
            // Maximized tab: no sidebar involved. Close the current tab. The tabs API
            // has no user-gesture gating, so this is safe after the async sendMessage.
            console.log('[NevoFlux] Minimize from maximized tab - closing current tab');
            browser.tabs.getCurrent().then(tab => {
                if (tab && tab.id) {
                    browser.tabs.remove(tab.id).catch(e => console.warn('[NevoFlux] close tab failed:', e));
                }
            }).catch(e => console.warn('[NevoFlux] get current tab failed:', e));
        } else {
            // Sidebar: close it (user gesture still valid since no await yet).
            if (browser.sidebarAction && browser.sidebarAction.close) {
                browser.sidebarAction.close().catch(e => console.warn('[NevoFlux] close failed:', e));
            }
        }
    }, true); // capture phase
})();

// Theme-follow: mirror Website-appearance (light/dark) and the active tab's
// boost accent into CSS signals consumed by nf-theme.css. Progressive
// enhancement — any failure leaves the sidebar on its built-in theme.
(async function initThemeFollow() {
    try {
        if (typeof browser === 'undefined' ||
            !browser.nevoflux ||
            typeof browser.nevoflux.getThemeContext !== 'function') {
            return;
        }

        const { computeThemeVars } = await import('./theme-color.mjs');

        const urlParams = new URLSearchParams(window.location.search);
        // Maximized mode: pinned to the originating tab. Sidebar mode: track
        // the active tab of this sidebar's own window.
        const fixedTabId = urlParams.get('mode') === 'maximized'
            ? (parseInt(urlParams.get('target_tab_id'), 10) || null)
            : null;
        let windowId = null;
        if (fixedTabId === null) {
            windowId = (await browser.windows.getCurrent()).id;
        }

        // Every override key computeThemeVars may emit; keys absent from the
        // current result must be removed or stale boost styling would stick.
        const OVERRIDE_KEYS = [
            '--nevo-background', '--nevo-surface', '--nevo-surface-hover',
            '--nevo-surface-active', '--nevo-text', '--nevo-text-secondary',
            '--nevo-border', '--nevo-font-family', '--nf-zoom',
        ];

        function applyThemeVars(vars) {
            const root = document.documentElement;
            root.dataset.nfScheme = vars.scheme;
            const map = {
                '--nf-accent': vars.accent,
                '--nf-accent-hover': vars.accentHover,
                '--nf-accent-light': vars.accentLight,
                '--nf-accent-lighter': vars.accentLighter,
            };
            for (const [prop, value] of Object.entries(map)) {
                if (value) {
                    root.style.setProperty(prop, value);
                } else {
                    root.style.removeProperty(prop);
                }
            }
            const overrides = vars.overrides || {};
            for (const prop of OVERRIDE_KEYS) {
                if (overrides[prop]) {
                    root.style.setProperty(prop, overrides[prop]);
                } else {
                    root.style.removeProperty(prop);
                }
            }
        }

        async function currentTabId() {
            if (fixedTabId !== null) return fixedTabId;
            const [tab] = await browser.tabs.query({ windowId, active: true });
            return tab ? tab.id : null;
        }

        // seq guard: only the latest in-flight refresh may apply (tab switches
        // can outrace the async query chain).
        let seq = 0;
        async function refresh() {
            const mySeq = ++seq;
            try {
                const tabId = await currentTabId();
                const ctx = await browser.nevoflux.getThemeContext(tabId ?? undefined);
                if (mySeq === seq && ctx) {
                    applyThemeVars(computeThemeVars(ctx));
                }
            } catch (e) {
                console.warn('[NevoFlux] theme refresh failed:', e);
            }
        }

        // Debounce: boost editor sliders fire zen-boosts-update continuously.
        let debounceTimer = null;
        function scheduleRefresh() {
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(refresh, 120);
        }

        browser.tabs.onActivated.addListener((info) => {
            if (fixedTabId !== null ? info.tabId === fixedTabId
                                    : info.windowId === windowId) {
                scheduleRefresh();
            }
        });
        browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
            if (!changeInfo.url) return;
            if (fixedTabId !== null ? tabId === fixedTabId
                                    : (tab.windowId === windowId && tab.active)) {
                scheduleRefresh();
            }
        });
        if (browser.nevoflux.onThemeContextChanged) {
            browser.nevoflux.onThemeContextChanged.addListener(scheduleRefresh);
        }

        refresh();
    } catch (e) {
        console.warn('[NevoFlux] theme-follow init failed:', e);
    }
})();
