/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/*
 * Hand-written boot code for the chat sidebar, kept OUTSIDE init.js on
 * purpose: init.js is regenerated by trunk + fix-csp.sh on every dioxus
 * rebuild (fix-csp overwrites it with the extracted wasm loader), which used
 * to clobber these handlers until they were re-merged by hand. This file is
 * hand-maintained in wasm/chat-sidebar/ (like nf-theme.css/theme-color.mjs)
 * and referenced by a plain <script> tag in the trunk source index.html, so
 * rebuilds keep the reference and never touch the content.
 */

// Maximize button click handler - MUST be synchronous to preserve user gesture
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.maximize-btn');
        if (!button) return;

        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('mode') === 'maximized') return;

        event.preventDefault();
        event.stopPropagation();

        console.log('[NevoFlux] Maximize clicked - synchronous handler');

        // Get data SYNCHRONOUSLY from window globals (set by WASM)
        const sessionId = window.__nevoflux_session_id || '';
        const targetTabId = window.__nevoflux_target_tab_id || 0;

        // Build URL synchronously
        const baseUrl = window.location.href.split('?')[0];
        const newUrl = `${baseUrl}?mode=maximized&session_id=${sessionId}&target_tab_id=${targetTabId}&source_tab_id=${targetTabId}`;

        console.log('[NevoFlux] Opening maximized view:', newUrl);

        // Open tab FIRST using window.open (synchronous, executes before close destroys context)
        window.open(newUrl, '_blank');

        // Then close sidebar (user gesture still valid since no await yet)
        if (browser.sidebarAction && browser.sidebarAction.close) {
            browser.sidebarAction.close().catch(e => console.warn('[NevoFlux] close failed:', e));
        }
    }, true); // capture phase
})();

// Scheduled-jobs (calendar) button click handler - MUST be synchronous to
// preserve the user gesture. Mirrors the maximize handler: the Rust
// try_close_sidebar_sync() close is CSP-dead (js_sys::eval is blocked by the
// extension CSP), so the sidebar close has to happen here in plain JS, inside
// the gesture. Same flow as maximize but deep-links the Jobs panel
// (&panel=jobs). Only present in the docked form (the button is hidden when
// maximized, where LeftMenu owns Schedule Jobs), so the maximized guard is
// belt-and-braces.
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.jobs-btn');
        if (!button) return;

        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('mode') === 'maximized') return;

        event.preventDefault();
        event.stopPropagation();

        console.log('[NevoFlux] Schedule Jobs clicked - synchronous handler');

        // Get data SYNCHRONOUSLY from window globals (set by WASM)
        const sessionId = window.__nevoflux_session_id || '';
        const targetTabId = window.__nevoflux_target_tab_id || 0;

        // Build URL synchronously, deep-linking the Jobs panel.
        const baseUrl = window.location.href.split('?')[0];
        const newUrl = `${baseUrl}?mode=maximized&session_id=${sessionId}&target_tab_id=${targetTabId}&source_tab_id=${targetTabId}&panel=jobs`;

        console.log('[NevoFlux] Opening maximized Jobs view:', newUrl);

        // Open tab FIRST using window.open (synchronous, executes before close destroys context)
        window.open(newUrl, '_blank');

        // Then close sidebar (user gesture still valid since no await yet)
        if (browser.sidebarAction && browser.sidebarAction.close) {
            browser.sidebarAction.close().catch(e => console.warn('[NevoFlux] close failed:', e));
        }
    }, true); // capture phase
})();

// Restore button click handler - MUST be synchronous to preserve user gesture
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.restore-btn');
        if (!button) return;

        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get('mode') !== 'maximized') return;

        event.preventDefault();
        event.stopPropagation();

        console.log('[NevoFlux] Restore clicked - synchronous handler');

        // Get source_tab_id from URL params
        const sourceTabId = parseInt(urlParams.get('source_tab_id')) || 0;

        // Open sidebar FIRST - this requires user gesture
        if (browser.sidebarAction && browser.sidebarAction.open) {
            browser.sidebarAction.open().catch(e => console.warn('[NevoFlux] open failed:', e));
        }

        // Then activate source tab and close this tab (no user gesture needed)
        if (sourceTabId > 0) {
            browser.tabs.update(sourceTabId, { active: true }).catch(e => console.warn('[NevoFlux] activate tab failed:', e));
        }

        // Close the maximized tab. Primary path is tabs.remove via getCurrent();
        // but browser.tabs.getCurrent() can resolve to undefined for some
        // extension-page-in-tab contexts, in which case the old code silently
        // skipped the close (tab stayed open, no error logged). These tabs were
        // opened via window.open(), so they are script-closeable — window.close()
        // is the robust fallback whenever getCurrent() yields no tab or remove fails.
        browser.tabs.getCurrent().then(tab => {
            if (tab && tab.id) {
                console.log('[NevoFlux] Restore: closing maximized tab via tabs.remove', tab.id);
                browser.tabs.remove(tab.id).catch(e => {
                    console.warn('[NevoFlux] close tab failed, falling back to window.close():', e);
                    try { window.close(); } catch (_) {}
                });
            } else {
                console.warn('[NevoFlux] Restore: getCurrent() returned no tab, using window.close()');
                try { window.close(); } catch (e) { console.warn('[NevoFlux] window.close failed:', e); }
            }
        }).catch(e => {
            console.warn('[NevoFlux] get current tab failed, using window.close():', e);
            try { window.close(); } catch (_) {}
        });
    }, true); // capture phase
})();

// Minimize button click handler - MUST be synchronous to preserve user gesture.
// Mirrors the maximize handler above: this file owns the whole minimize flow in
// plain JS because the extension CSP (script-src 'self' 'wasm-unsafe-eval') blocks
// js_sys::eval, which is why the Rust try_close_sidebar_sync() close was a silent
// no-op. Capture-phase + stopPropagation bypasses the Dioxus onclick so this runs
// once and there is no double-send.
(function() {
    document.addEventListener('click', function(event) {
        const button = event.target.closest('.minimize-btn');
        if (!button) return;

        event.preventDefault();
        event.stopPropagation();

        const urlParams = new URLSearchParams(window.location.search);
        const isMaximized = urlParams.get('mode') === 'maximized';

        console.log('[NevoFlux] Minimize clicked - synchronous handler (maximized=' + isMaximized + ')');

        // Gather session context so the background can restore the right session when
        // the avatar Maximize button is clicked. Window globals cover sidebar mode;
        // URL params cover the maximized-tab mode (mirroring how the maximize handler
        // sources them in the sidebar branch above).
        const sessionId = window.__nevoflux_session_id || urlParams.get('session_id') || '';
        const targetTabId = window.__nevoflux_target_tab_id || parseInt(urlParams.get('target_tab_id') || '0', 10) || 0;

        // Notify the background FIRST to show the floating avatar + start the daemon
        // keepalive. sendMessage returns a Promise, but the send itself is dispatched
        // synchronously to the browser IPC while the gesture is still active, so the
        // message survives the imminent teardown from the close/remove below.
        if (browser.runtime && browser.runtime.sendMessage) {
            browser.runtime.sendMessage({ type: 'bg:agent_minimize', session_id: sessionId, target_tab_id: targetTabId }).catch(e => console.warn('[NevoFlux] minimize sendMessage failed:', e));
        }

        if (isMaximized) {
            // Maximized tab: no sidebar involved. Close the current tab. The tabs API
            // has no user-gesture gating, so this is safe after the async sendMessage.
            console.log('[NevoFlux] Minimize from maximized tab - closing current tab');
            browser.tabs.getCurrent().then(tab => {
                if (tab && tab.id) {
                    browser.tabs.remove(tab.id).catch(e => console.warn('[NevoFlux] close tab failed:', e));
                }
            }).catch(e => console.warn('[NevoFlux] get current tab failed:', e));
        } else {
            // Sidebar: close it (user gesture still valid since no await yet).
            if (browser.sidebarAction && browser.sidebarAction.close) {
                browser.sidebarAction.close().catch(e => console.warn('[NevoFlux] close failed:', e));
            }
        }
    }, true); // capture phase
})();

// Theme-follow: mirror Website-appearance (light/dark) and the active tab's
// boost accent into CSS signals consumed by nf-theme.css. Progressive
// enhancement — any failure leaves the sidebar on its built-in theme.
(async function initThemeFollow() {
    try {
        if (typeof browser === 'undefined' ||
            !browser.nevoflux ||
            typeof browser.nevoflux.getThemeContext !== 'function') {
            return;
        }

        const { computeThemeVars } = await import('./theme-color.mjs');

        const urlParams = new URLSearchParams(window.location.search);
        // Maximized mode: pinned to the originating tab. Sidebar mode: track
        // the active tab of this sidebar's own window.
        const fixedTabId = urlParams.get('mode') === 'maximized'
            ? (parseInt(urlParams.get('target_tab_id'), 10) || null)
            : null;
        let windowId = null;
        if (fixedTabId === null) {
            windowId = (await browser.windows.getCurrent()).id;
        }

        // Every override key computeThemeVars may emit; keys absent from the
        // current result must be removed or stale boost styling would stick.
        const OVERRIDE_KEYS = [
            '--nevo-background', '--nevo-surface', '--nevo-surface-hover',
            '--nevo-surface-active', '--nevo-text', '--nevo-text-secondary',
            '--nevo-border', '--nevo-font-family', '--nf-zoom',
        ];

        function applyThemeVars(vars) {
            const root = document.documentElement;
            root.dataset.nfScheme = vars.scheme;
            const map = {
                '--nf-accent': vars.accent,
                '--nf-accent-hover': vars.accentHover,
                '--nf-accent-light': vars.accentLight,
                '--nf-accent-lighter': vars.accentLighter,
            };
            for (const [prop, value] of Object.entries(map)) {
                if (value) {
                    root.style.setProperty(prop, value);
                } else {
                    root.style.removeProperty(prop);
                }
            }
            const overrides = vars.overrides || {};
            for (const prop of OVERRIDE_KEYS) {
                if (overrides[prop]) {
                    root.style.setProperty(prop, overrides[prop]);
                } else {
                    root.style.removeProperty(prop);
                }
            }
        }

        async function currentTabId() {
            if (fixedTabId !== null) return fixedTabId;
            const [tab] = await browser.tabs.query({ windowId, active: true });
            return tab ? tab.id : null;
        }

        // seq guard: only the latest in-flight refresh may apply (tab switches
        // can outrace the async query chain).
        let seq = 0;
        async function refresh() {
            const mySeq = ++seq;
            try {
                const tabId = await currentTabId();
                const ctx = await browser.nevoflux.getThemeContext(tabId ?? undefined);
                if (mySeq === seq && ctx) {
                    applyThemeVars(computeThemeVars(ctx));
                }
            } catch (e) {
                console.warn('[NevoFlux] theme refresh failed:', e);
            }
        }

        // Debounce: boost editor sliders fire zen-boosts-update continuously.
        let debounceTimer = null;
        function scheduleRefresh() {
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(refresh, 120);
        }

        browser.tabs.onActivated.addListener((info) => {
            if (fixedTabId !== null ? info.tabId === fixedTabId
                                    : info.windowId === windowId) {
                scheduleRefresh();
            }
        });
        browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
            if (!changeInfo.url) return;
            if (fixedTabId !== null ? tabId === fixedTabId
                                    : (tab.windowId === windowId && tab.active)) {
                scheduleRefresh();
            }
        });
        if (browser.nevoflux.onThemeContextChanged) {
            browser.nevoflux.onThemeContextChanged.addListener(scheduleRefresh);
        }

        refresh();
    } catch (e) {
        console.warn('[NevoFlux] theme-follow init failed:', e);
    }
})();

// Voice input (speech-to-speech uplink/downlink) — MUST start the microphone
// synchronously inside the click, for the same reason as the handlers above:
// getUserMedia is gated on a user gesture, and the gesture does not survive the
// awaits inside the speech client's startup (AudioContext + audioWorklet
// addModule + Worker spawn). Requesting the stream here and handing it over is
// the whole reason SpeechClient.start() accepts an existing stream.
//
// This handler deliberately does NOT stopPropagation: the Dioxus onclick only
// flips a local `is_recording` signal (pure styling), so letting it run keeps
// the button's look in sync for free. The pipeline itself lives here.
(function initVoiceInput() {
    let busy = false;      // 起停过程中,忽略连点
    let syncing = false;   // 我们自己发出的 click(把按钮视觉掰回来),不当作用户操作

    // 语音自行停止(静默超时、启动失败)时,Rust 那边的 is_recording 还停在
    // "recording" —— 它只由点击翻转。补发一次 click 是唯一不改 WASM 就能把两边
    // 状态对齐的办法。
    function resyncButton() {
        const btn = document.querySelector('.voice-send-button.voice-mode.recording');
        if (!btn) return;
        syncing = true;
        try { btn.click(); } finally { syncing = false; }
    }

    document.addEventListener('click', function(event) {
        const button = event.target.closest('.voice-send-button.voice-mode');
        if (!button || syncing || busy) return;

        const wasRecording = button.classList.contains('recording');
        busy = true;

        if (wasRecording) {
            import('./nf-voice.mjs')
                .then(m => m.stopVoice())
                .catch(e => console.warn('[NevoFlux] voice stop failed:', e))
                .finally(() => { busy = false; });
            return;
        }

        // 手势还在的这一刻发起授权。await 之后再发就晚了 —— 实测表现是
        // getUserMedia 既不 resolve 也不 reject 地挂住。
        const pending = navigator.mediaDevices.getUserMedia({
            audio: {
                echoCancellation: true,
                noiseSuppression: true,
                autoGainControl: true,
                channelCount: 1,
            },
        });

        import('./nf-voice.mjs')
            .then(m => pending.then(stream => m.startVoice({
                stream,
                sessionId: window.__nevoflux_session_id || '',
                onStopped: resyncButton,
            })))
            .catch(e => {
                console.warn('[NevoFlux] voice start failed:', e);
                // 流可能已经开了但后面失败了:不关掉的话录音指示器会一直亮着。
                pending.then(s => s.getTracks().forEach(t => t.stop())).catch(() => {});
                resyncButton();
            })
            .finally(() => { busy = false; });
    }, true); // capture phase

    // 无人值守验证用的入口。
    //
    // 上面那条路要求一次真实点击,而这台机器上没有人点、也没有麦克风。用文件
    // 代声源跑同一段接线,验证的是「侧边栏里这套接得对不对」——采集→VAD→上行→
    // 转写→**当作一条普通消息提交**→回答出声,不是声学。
    (async function maybeVoiceSelfTest() {
        const params = new URLSearchParams(window.location.search);
        if (!params.has('voicetest')) return;
        const wait = (ms) => new Promise(r => setTimeout(r, ms));
        try {
            // session id 由 WASM 侧异步写进 window;它是「同一条 history」的凭据,
            // 等不到就不是一次有意义的验证。
            for (let i = 0; i < 100 && !window.__nevoflux_session_id; i++) await wait(200);
            const sessionId = window.__nevoflux_session_id || '';
            const m = await import('./nf-voice.mjs');
            await m.startVoice({
                fileUrl: new URL('../../lib/speech/fixtures/zh.wav', import.meta.url).href,
                sink: 'stream',
                sessionId,
            });

            // 上行:等一条被采纳的转写提交出去。
            let up = null;
            for (let i = 0; i < 120; i++) {
                await wait(500);
                const st = m.stats();
                if (st.submitted > 0) { up = st; break; }
            }

            // 下行:直接让它念一段英文。回答本身是否出声取决于 agent 用什么语言
            // 作答 —— Kokoro 只会英文,中文要等 P1 的 MOSS,那是模型的缺口,
            // 不是接线的。所以这一段单独验证播放通路。
            m.speak('<speak>Voice input is wired into the sidebar.</speak>Wired.');
            for (let i = 0; i < 60; i++) {
                await wait(500);
                if (m.stats().played > 0) break;
            }

            const verdict = { sessionId: !!sessionId, uplink: up, final: m.stats() };
            console.log('[VOICE-TEST]', JSON.stringify(verdict));
        } catch (e) {
            console.log('[VOICE-TEST]', JSON.stringify({ error: String(e && e.message || e) }));
        }
    })();
})();
